theme: jekyll-theme-minimal                                                                                                                                                         
title: FocusCoach Legal                                                                                                                                                             
description: Privacy Policy and Terms of Service                                                                                                                                    
                                                     
